version: '3'

services:
  mysql-8-a:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: vapor_database
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
    ports:
      - 3306:3306
  mysql-8-b:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: vapor_database
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
    ports:
      - 3307:3306
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: vapor_database
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
    ports:
      - 3306:3306
  test:
    privileged: true
    image: vapor/swift:5.0
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - mysql


